# Generated by Django 5.0.4 on 2024-04-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('viloyat', models.CharField(choices=[('qashqadaryo', 'Qashqadaryo')], max_length=20)),
                ('tuman', models.CharField(choices=[('shahrisabz', 'Shahrisabz')], max_length=20)),
                ('maktab', models.CharField(choices=[('15-maktab', '15-Maktab')], max_length=20)),
                ('snif', models.CharField(choices=[('1-snif', '1-Snif')], max_length=20)),
                ('harf', models.CharField(choices=[('a', 'A')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
