# Generated by Django 5.0.4 on 2024-04-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofil',
            old_name='name',
            new_name='username',
        ),
    ]
